schema: src/graphql/generated/schema.gql
documents: src/**/*.tsx
generates:
  src/graphql/generated/client-types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo